#!/usr/bin/env bash
# PiHerder — Cloud Agent install (idempotent repository bootstrap).
# Runs after checkout to prepare system services, the Python venv, vendored
# frontend assets, local data dirs, and a gitignored dev .env. Safe to re-run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export DEBIAN_FRONTEND=noninteractive

echo "==> System packages (PostgreSQL, Redis, build deps)…"
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends \
  postgresql postgresql-contrib \
  redis-server \
  python3-venv python3-dev build-essential libpq-dev \
  rsync openssh-client iputils-ping dnsutils curl ca-certificates

echo "==> Python virtualenv + locked dependencies…"
python3 -m venv .venv
./.venv/bin/python -m pip install --upgrade pip setuptools wheel
# requirements.lock.txt = runtime + dev (pytest, ruff, coverage) with hashes.
./.venv/bin/pip install --require-hashes -r requirements.lock.txt
# Install the app itself without re-resolving dependencies.
./.venv/bin/pip install --no-deps --no-build-isolation -e .

echo "==> Vendored frontend JS (offline HTMX / Alpine / xterm)…"
if [ ! -f app/static/htmx.min.js ] || [ ! -f app/static/alpine.min.js ]; then
  bash scripts/vendor_cdns.sh || echo "   (vendor step failed — UI JS may be missing; re-run scripts/vendor_cdns.sh)"
fi

echo "==> Local runtime directories…"
mkdir -p piherder_data/avatars backups piherder_backups

echo "==> Dev .env (generated once; gitignored)…"
if [ ! -f .env ]; then
  MASTER_KEY="$(./.venv/bin/python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
  SECRET="$(./.venv/bin/python -c 'import secrets; print(secrets.token_hex(32))')"
  cat > .env <<EOF
# Local Cloud Agent dev environment (generated by .cursor/install.sh; .env is gitignored).
# Fresh random keys per environment build — never reuse for a real fleet.
PIHERDER_MASTER_KEY=${MASTER_KEY}
SECRET_KEY=${SECRET}
DATABASE_URL=postgresql://piherder:piherder@127.0.0.1:5432/piherder
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/0
REDIS_URL=redis://127.0.0.1:6379/0
DATA_ROOT=${REPO_ROOT}/piherder_data
BACKUP_ROOT=${REPO_ROOT}/backups
HERDER_BACKUP_ROOT=${REPO_ROOT}/piherder_backups
ALLOW_OPEN_REGISTRATION=false
PIHERDER_UPDATE_CHECK=false
COOKIE_SECURE=false
CADDY_ADMIN_URL=
TZ=Etc/UTC
EOF
  echo "   wrote .env"
else
  echo "   .env already present — leaving as-is"
fi

echo "==> install complete."
